/*
===========================================================
Project : Olist Brazilian E-commerce Analysis
Section : Sales & Revenue Analysis
Database: PostgreSQL
===========================================================
*/

-- ===========================================================
-- Q1. How much revenue has the company generated?
-- Purpose: Measure the total revenue generated by the marketplace.
-- ===========================================================

SELECT
    ROUND(SUM(price)::numeric, 2) AS total_revenue
FROM order_items;

-- ===========================================================
-- Q2. Is revenue growing or declining over time?
-- Purpose: Track monthly revenue trends to evaluate business growth and identify seasonal sales patterns.
-- ===========================================================

SELECT
    DATE_TRUNC('month', o.order_purchase_timestamp) AS month,
    ROUND(SUM(oi.price)::numeric, 2) AS revenue
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
GROUP BY month
ORDER BY month;

-- ===========================================================
-- Q3. Which months generated the highest revenue?
-- Purpose: Identify the highest-performing months to support sales planning and business strategy.
-- ===========================================================

SELECT
    TO_CHAR(o.order_purchase_timestamp::timestamp, 'YYYY-MM') AS month,
    SUM(oi.price) AS total_revenue
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY month
ORDER BY total_revenue DESC;

-- ===========================================================
-- Q4. Which product categories generate the highest revenue?
-- Purpose: Identify the top revenue-generating product categories to support product strategy, inventory planning, and marketing decisions.
-- ===========================================================

SELECT
    ct.product_category_name_english,
    SUM(oi.price) AS revenue
FROM products p
JOIN category_translation ct
    ON p.product_category_name = ct.product_category_name
JOIN order_items oi
    ON p.product_id = oi.product_id
JOIN orders o
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY ct.product_category_name_english
ORDER BY revenue DESC
LIMIT 10;

-- ===========================================================
-- Q5. Which product categories sell the most items?
-- Purpose: Identify the best-selling product categories based on sales volume to support inventory management and product demand analysis.
-- ===========================================================

SELECT
    p.product_category_name,
    ct.product_category_name_english,
    COUNT(oi.product_id) AS total_item_sold
FROM products p
JOIN category_translation ct
    ON p.product_category_name = ct.product_category_name
JOIN order_items oi
    ON p.product_id = oi.product_id
JOIN orders o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY
    p.product_category_name,
    ct.product_category_name_english
ORDER BY total_item_sold DESC;

-- ===========================================================
-- Q6. Which product categories generate high revenue despite having low sales volume?
-- Purpose: Identify premium product categories that earn high revenue from fewer sales, helping optimize pricing and product positioning.
-- ===========================================================

SELECT
    ct.product_category_name_english,
    SUM(oi.price) AS total_revenue,
    COUNT(oi.product_id) AS total_items_sold,
    SUM(oi.price) / COUNT(oi.product_id) AS average_selling_price
FROM products p
JOIN category_translation ct
    ON p.product_category_name = ct.product_category_name
JOIN order_items oi
    ON oi.product_id = p.product_id
JOIN orders o
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY ct.product_category_name_english
ORDER BY
    total_revenue DESC,
    total_items_sold ASC;

-- ===========================================================
-- Q7. Which product categories have the highest Average Selling Price (ASP)?
-- Purpose: Identify premium product categories with the highest average selling price to support pricing strategy and product portfolio analysis.
-- ===========================================================

SELECT
    ct.product_category_name_english,
    ROUND(
        (SUM(oi.price) / COUNT(oi.product_id))::numeric,
        2
    ) AS average_selling_price
FROM products p
JOIN category_translation ct
    ON p.product_category_name = ct.product_category_name
JOIN order_items oi
    ON oi.product_id = p.product_id
JOIN orders o
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY ct.product_category_name_english
ORDER BY average_selling_price DESC;

-- ===========================================================
-- Q8. Which products generate the highest revenue?
-- Purpose: Identify the top revenue-generating products to evaluate product performance and support merchandising, inventory, and promotional decisions.
-- ===========================================================

SELECT
    p.product_id,
    ct.product_category_name_english,
    SUM(oi.price) AS total_revenue
FROM products p
JOIN category_translation ct
    ON p.product_category_name = ct.product_category_name
JOIN order_items oi
    ON p.product_id = oi.product_id
JOIN orders o
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY
    p.product_id,
    ct.product_category_name_english
ORDER BY total_revenue DESC
LIMIT 10;

-- ===========================================================
-- Q9. Which products generate high revenue despite having low sales volume?
-- Purpose: Identify high-value products that generate significant revenue from fewer sales to support premium product strategy and pricing decisions.
-- ===========================================================

SELECT
    p.product_id,
    ct.product_category_name_english,
    SUM(oi.price) AS total_revenue,
    COUNT(oi.product_id) AS items_sold
FROM products p
JOIN category_translation ct
    ON p.product_category_name = ct.product_category_name
JOIN order_items oi
    ON oi.product_id = p.product_id
JOIN orders o
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY
    p.product_id,
    ct.product_category_name_english
ORDER BY
    total_revenue DESC,
    items_sold ASC;

-- ===========================================================
-- Q10. Which sellers generate the highest revenue?
-- Purpose: Identify the top-performing sellers by revenue to evaluate seller performance and support partnership and business growth decisions.
-- ===========================================================

SELECT
    s.seller_id,
    SUM(oi.price) AS total_revenue
FROM sellers s
JOIN order_items oi
    ON s.seller_id = oi.seller_id
JOIN orders o
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY s.seller_id
ORDER BY total_revenue DESC
LIMIT 10;

-- ===========================================================
-- Q11. Which sellers processed the highest number of orders?
-- Purpose: Identify sellers with the highest order volume to evaluate operational performance and marketplace contribution.
-- ===========================================================

SELECT
    s.seller_id,
    COUNT(DISTINCT oi.order_id) AS total_order
FROM sellers s
JOIN order_items oi
    ON s.seller_id = oi.seller_id
JOIN orders o
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY s.seller_id
ORDER BY total_order DESC
LIMIT 10;

-- ===========================================================
-- Q12. Which sellers have the highest Average Order Value (AOV)?
-- Purpose: Identify sellers with the highest average revenue per order to evaluate sales efficiency and premium product performance.
-- ===========================================================

SELECT
    s.seller_id,
    ROUND(
        (SUM(oi.price) / COUNT(DISTINCT oi.order_id))::numeric,
        2
    ) AS average_order_value
FROM sellers s
JOIN order_items oi
    ON s.seller_id = oi.seller_id
JOIN orders o
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY s.seller_id
ORDER BY average_order_value DESC
LIMIT 10;

-- ===========================================================
-- Q13. Which sellers generate high revenue despite processing fewer orders?
-- Purpose: Identify high-performing sellers who generate significant revenue with fewer orders, helping evaluate seller efficiency and premium product offerings.
-- ===========================================================

WITH sellers_metric AS (
    SELECT
        s.seller_id,
        SUM(oi.price) AS total_revenue,
        COUNT(DISTINCT oi.order_id) AS total_orders
    FROM sellers s
    JOIN order_items oi
        ON s.seller_id = oi.seller_id
    JOIN orders o
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY s.seller_id
)

SELECT
    seller_id,
    total_revenue,
    total_orders
FROM sellers_metric
WHERE total_revenue > (
    SELECT AVG(total_revenue)
    FROM sellers_metric
)
AND total_orders < (
    SELECT AVG(total_orders)
    FROM sellers_metric
)
ORDER BY total_revenue DESC;
