/*
===========================================================
Project : Olist Brazilian E-commerce Analysis
Section : Payment Analysis
Database: PostgreSQL
===========================================================
*/

-- ===========================================================
-- Q1. Which payment method is used the most by customers?
-- Purpose: Identify the most frequently used payment method.
-- ===========================================================

SELECT
    p.payment_type,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM payments p
JOIN orders o
    ON p.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY p.payment_type
ORDER BY total_orders DESC;

-- ===========================================================
-- Q2. Which payment methods generate the most revenue?
-- Purpose: Compare revenue generated by each payment method.
-- ===========================================================

SELECT
    p.payment_type,
    ROUND(SUM(p.payment_value)::numeric, 2) AS total_revenue
FROM payments p
JOIN orders o
    ON p.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY p.payment_type
ORDER BY total_revenue DESC;

-- ===========================================================
-- Q3. What is the average payment value for each payment method?
-- Purpose: Measure the average payment amount by payment method.
-- ===========================================================

SELECT
    p.payment_type,
    ROUND(AVG(p.payment_value)::numeric, 2) AS avg_payment_value
FROM payments p
JOIN orders o
    ON p.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY p.payment_type
ORDER BY avg_payment_value DESC;

-- ===========================================================
-- Q4. Which payment methods are mostly used for installment payments?
-- Purpose: Compare average installment counts across payment methods.
-- ===========================================================

SELECT
    p.payment_type,
    ROUND(
        AVG(p.payment_installments)::numeric,
        2
    ) AS avg_payment_installments
FROM payments p
JOIN orders o
    ON p.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY p.payment_type
ORDER BY avg_payment_installments DESC;

-- ===========================================================
-- Q5. How much revenue comes from one-time payments vs installment payments?
-- Purpose: Compare revenue generated by one-time and installment payments.
-- ===========================================================

SELECT
    CASE
        WHEN p.payment_installments = 1 THEN 'One-time Payment'
        ELSE 'Installment Payment'
    END AS payment_category,
    ROUND(SUM(p.payment_value)::numeric, 2) AS total_revenue
FROM payments p
JOIN orders o
    ON p.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY
    CASE
        WHEN p.payment_installments = 1 THEN 'One-time Payment'
        ELSE 'Installment Payment'
    END;

-- ===========================================================
-- Q6. Which payment methods are used for high-value orders?
-- Purpose: Identify payment methods commonly used for orders above 500.
-- ===========================================================

SELECT
    p.payment_type,
    COUNT(DISTINCT p.order_id) AS high_value_orders,
    ROUND(
        AVG(p.payment_value)::numeric,
        2
    ) AS avg_order_value
FROM payments p
JOIN orders o
    ON p.order_id = o.order_id
WHERE o.order_status = 'delivered'
  AND p.payment_value > 500
GROUP BY p.payment_type
ORDER BY high_value_orders DESC;

-- ===========================================================
-- Q7. How has revenue from each payment method changed over time?
-- Purpose: Analyze monthly revenue trends by payment method.
-- ===========================================================

SELECT
    DATE_TRUNC('month', o.order_purchase_timestamp) AS month,
    p.payment_type,
    ROUND(
        SUM(p.payment_value)::numeric,
        2
    ) AS total_revenue
FROM payments p
JOIN orders o
    ON p.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY
    DATE_TRUNC('month', o.order_purchase_timestamp),
    p.payment_type
ORDER BY
    month,
    p.payment_type;

-- ===========================================================
-- Q8. Rank payment methods by total revenue.
-- Purpose: Rank payment methods based on revenue generated.
-- ===========================================================

SELECT
    p.payment_type,
    ROUND(
        SUM(p.payment_value)::numeric,
        2
    ) AS total_revenue,
    RANK() OVER (
        ORDER BY SUM(p.payment_value) DESC
    ) AS payment_method_rank
FROM payments p
JOIN orders o
    ON p.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY p.payment_type
ORDER BY total_revenue DESC;
